import type { Seed } from "./types";

// Original editorial prompts. Variants attempt to preserve the policy question;
// users can reclassify an imperfect paraphrase as framing before comparing it.
type Row = [
  title: string,
  question: string,
  first: string,
  second: string,
  options?: string[],
];
const groups: [string, Row[]][] = [
  [
    "AI & automation",
    [
      [
        "Pausing frontier AI",
        "Should development of more powerful AI models be paused?",
        "Should the development of more powerful AI models be put on hold?",
        "Is a pause in developing more powerful AI models warranted?",
      ],
      [
        "Permission to train",
        "Should AI companies need permission to train on copyrighted work?",
        "Should training AI on copyrighted work require the copyright holder’s consent?",
        "Should copyright holders have to authorize the use of their work in AI training?",
      ],
      [
        "Open model weights",
        "Should powerful AI model weights be publicly available?",
        "Should the weights of powerful AI models be accessible to the public?",
        "Is public access to powerful AI model weights desirable?",
      ],
      [
        "Data center vetoes",
        "Should local communities be able to block new AI data centers?",
        "Should communities have the right to reject new AI data centers in their area?",
        "Should approval from the local community be required for a new AI data center?",
      ],
      [
        "AI companions for minors",
        "Should companies offer AI companion apps to people under 18?",
        "Should people younger than 18 be allowed to use commercial AI companion apps?",
        "Should commercial AI companions be available to minors?",
      ],
      [
        "Automation tax",
        "Should companies pay an additional tax when AI replaces their workers?",
        "Should replacing workers with AI trigger an extra tax for employers?",
        "Should employers owe a special tax for jobs they replace with AI?",
      ],
      [
        "AI in hiring",
        "Should employers use AI to reject job applicants without human review?",
        "Should AI be allowed to turn down job applicants without a person reviewing the decision?",
        "Is it acceptable for an employer to reject an applicant solely on an AI decision?",
      ],
      [
        "AI safety disclosure",
        "Should AI developers have to publish the results of their safety tests?",
        "Should disclosure of AI safety test results be mandatory for developers?",
        "Should developers be required to make their AI safety testing results public?",
      ],
      [
        "Who regulates AI?",
        "Which level of government should primarily regulate AI in the United States?",
        "Who should take the lead in regulating AI in the U.S.?",
        "Where should primary responsibility for U.S. AI regulation sit?",
        [
          "Federal government",
          "State governments",
          "Shared federal and state authority",
          "No dedicated AI regulation",
        ],
      ],
      [
        "AI and work",
        "What should be the main policy response to job losses caused by AI?",
        "Which policy should take priority when AI displaces workers?",
        "How should policymakers primarily respond to AI-driven job displacement?",
        [
          "Worker retraining",
          "Universal basic income",
          "Wage insurance",
          "Limits on automation",
        ],
      ],
    ],
  ],
  [
    "Speech & the internet",
    [
      [
        "Social media age limits",
        "Should social media be restricted to people aged 16 and older?",
        "Should people under 16 be barred from social media?",
        "Should 16 be the minimum age for using social media?",
      ],
      [
        "Anonymous accounts",
        "Should people be allowed to post anonymously on major social platforms?",
        "Should major social platforms permit anonymous posting?",
        "Should users of major social platforms be able to conceal their identity when posting?",
      ],
      [
        "Platform speech rules",
        "Should large social platforms be allowed to remove lawful political speech?",
        "Should major social platforms be permitted to take down political speech that is legal?",
        "Should a large social platform have the right to delete lawful political content?",
      ],
      [
        "Encrypted messages",
        "Should messaging services provide law enforcement a way to access encrypted messages?",
        "Should law enforcement have an access mechanism for encrypted messaging services?",
        "Should providers of encrypted messaging build in access for law enforcement?",
      ],
      [
        "Political deepfakes",
        "Should deceptive AI impersonations of political candidates be banned in campaign ads?",
        "Should campaign ads be prohibited from using deceptive AI-generated candidate impersonations?",
        "Should it be illegal to use misleading AI impersonations of candidates in election advertising?",
      ],
      [
        "Age checks online",
        "Should adult websites require users to prove their age?",
        "Should proof of age be mandatory for accessing adult websites?",
        "Should adult websites verify the age of everyone who visits?",
      ],
      [
        "Right to be forgotten",
        "Should people be able to require search engines to delist old, accurate stories about them?",
        "Should search engines have to remove links to old but accurate stories at the subject’s request?",
        "Should someone have a right to delist accurate older reporting about themselves from search results?",
      ],
      [
        "TikTok ownership",
        "Should TikTok be required to change ownership to operate in the United States?",
        "Should continued U.S. operation of TikTok depend on an ownership change?",
        "Should the U.S. make a change in TikTok’s ownership a condition of operating there?",
      ],
      [
        "Misinformation policy",
        "How should social platforms respond to legal but demonstrably false political claims?",
        "What should platforms do with lawful political statements that can be shown to be false?",
        "Which response should platforms prioritize for verifiably false political content that is legal?",
        [
          "Remove it",
          "Reduce its reach",
          "Add contextual labels",
          "Leave it unchanged",
        ],
      ],
      [
        "Online privacy",
        "Who should bear the main responsibility for protecting users’ online privacy?",
        "Who should be chiefly responsible for safeguarding privacy online?",
        "Where should the primary duty to protect internet users’ privacy lie?",
        [
          "Technology companies",
          "Government regulators",
          "Individual users",
          "An independent public body",
        ],
      ],
    ],
  ],
  [
    "Immigration & borders",
    [
      [
        "A path to citizenship",
        "Should undocumented immigrants who meet specified requirements have a path to citizenship?",
        "Should citizenship be available to undocumented immigrants who satisfy defined conditions?",
        "Should immigrants without legal status be eligible for citizenship if they meet set requirements?",
      ],
      [
        "Deportation priorities",
        "Should immigration enforcement prioritize people convicted of violent crimes?",
        "Should people with violent criminal convictions be the first priority for immigration enforcement?",
        "Should immigration authorities focus first on people convicted of violent offenses?",
      ],
      [
        "Work permits for asylum seekers",
        "Should asylum seekers be allowed to work while their claims are reviewed?",
        "Should people awaiting an asylum decision have permission to work?",
        "Should employment be permitted for asylum applicants during the review of their claims?",
      ],
      [
        "Birthright citizenship",
        "Should a child born in the United States receive citizenship regardless of their parents’ immigration status?",
        "Should U.S. birth confer citizenship without regard to the immigration status of the parents?",
        "Should all children born in the U.S. be citizens, whatever their parents’ legal status?",
      ],
      [
        "Sanctuary policies",
        "Should local police be required to help enforce federal immigration law?",
        "Should assisting with federal immigration enforcement be mandatory for local police?",
        "Should local law enforcement have a duty to support federal immigration enforcement?",
      ],
      [
        "Immigration detention",
        "Should asylum-seeking families be detained while their cases are decided?",
        "Should families seeking asylum be held in detention pending a decision?",
        "Should families remain in immigration detention during the review of their asylum cases?",
      ],
      [
        "Highly skilled visas",
        "Should the United States increase the number of visas for highly skilled workers?",
        "Should more U.S. visas be available to workers with advanced skills?",
        "Should the U.S. expand its visa supply for highly skilled employees?",
      ],
      [
        "Immigration raids at schools",
        "Should immigration enforcement actions be prohibited on school grounds?",
        "Should school grounds be off limits to immigration enforcement operations?",
        "Should immigration authorities be barred from conducting enforcement operations at schools?",
      ],
      [
        "Legal immigration levels",
        "How should the U.S. change the number of people admitted through legal immigration?",
        "What change should the United States make to legal immigration admissions?",
        "What should happen to the overall level of legal immigration into the U.S.?",
        ["Increase it", "Keep it about the same", "Decrease it"],
      ],
      [
        "ICE reform",
        "What should the United States do with Immigration and Customs Enforcement?",
        "What is the best policy for the future of ICE?",
        "How should the U.S. approach the future of its Immigration and Customs Enforcement agency?",
        [
          "Keep its current structure",
          "Reform its powers and oversight",
          "Replace it with a new agency",
          "Abolish its immigration enforcement function",
        ],
      ],
    ],
  ],
  [
    "Democracy & power",
    [
      [
        "Voter identification",
        "Should voters have to show government-issued photo identification to vote?",
        "Should presenting government-issued photo ID be required for voting?",
        "Should voting be conditional on showing a government-issued photo ID?",
      ],
      [
        "Mail voting",
        "Should every eligible voter be able to vote by mail without giving a reason?",
        "Should no-excuse mail voting be available to all eligible voters?",
        "Should eligible voters be allowed to request a mail ballot without explaining why?",
      ],
      [
        "Supreme Court terms",
        "Should U.S. Supreme Court justices serve fixed terms instead of lifetime appointments?",
        "Should fixed terms replace lifetime tenure on the U.S. Supreme Court?",
        "Should appointments to the Supreme Court be time-limited rather than lifelong?",
      ],
      [
        "Presidential immunity",
        "Should presidents be immune from criminal prosecution for official acts?",
        "Should official presidential actions be protected from criminal prosecution?",
        "Should a president’s official acts carry immunity from criminal charges?",
      ],
      [
        "Congressional stock trading",
        "Should members of Congress be prohibited from trading individual stocks?",
        "Should individual stock trading be banned for members of Congress?",
        "Should serving in Congress disqualify someone from buying and selling individual stocks?",
      ],
      [
        "Voting age",
        "Should the voting age in U.S. federal elections be lowered to 16?",
        "Should 16-year-olds be eligible to vote in U.S. federal elections?",
        "Should the United States let people vote in federal elections starting at age 16?",
      ],
      [
        "Electoral College",
        "Should the U.S. president be elected by a national popular vote?",
        "Should the nationwide popular vote determine who becomes U.S. president?",
        "Should the U.S. choose its president based on the total national popular vote?",
      ],
      [
        "Independent redistricting",
        "Should independent commissions draw congressional district boundaries?",
        "Should congressional maps be drawn by independent redistricting commissions?",
        "Should responsibility for drawing congressional districts belong to independent commissions?",
      ],
      [
        "Campaign finance",
        "Which approach to funding election campaigns should the U.S. prioritize?",
        "What should be the primary approach to campaign funding in U.S. elections?",
        "Which campaign-finance system should the United States favor?",
        [
          "Public funding",
          "Capped private donations",
          "Uncapped donations with disclosure",
          "A mix of public funding and capped donations",
        ],
      ],
      [
        "Filibuster reform",
        "What should the U.S. Senate do with the legislative filibuster?",
        "How should the Senate handle its legislative filibuster rule?",
        "Which approach to the Senate’s legislative filibuster is best?",
        [
          "Keep it unchanged",
          "Require a talking filibuster",
          "Exempt selected legislation",
          "End it",
        ],
      ],
    ],
  ],
  [
    "Rights & identity",
    [
      [
        "Abortion access",
        "Should abortion be legal during the first 12 weeks of pregnancy?",
        "Should people have legal access to abortion in the first 12 weeks of pregnancy?",
        "Should the law permit abortion within the first 12 weeks of a pregnancy?",
      ],
      [
        "Transgender athletes",
        "Should transgender women be eligible to compete in women’s elite sports?",
        "Should elite women’s sports allow transgender women to participate?",
        "Should transgender women have eligibility for elite athletic competitions in the women’s category?",
      ],
      [
        "Gender care for minors",
        "Should adolescents be able to receive gender-related medical treatment with parental consent and specialist approval?",
        "Should parental consent and specialist approval allow adolescents to access gender-related medical care?",
        "Should gender-related medical treatment be available to adolescents when parents consent and specialists approve?",
      ],
      [
        "Affirmative action",
        "Should universities consider race as one factor in admissions?",
        "Should race be a permissible consideration among university admissions criteria?",
        "Should college admissions be allowed to take an applicant’s race into account as one factor?",
      ],
      [
        "Reparations",
        "Should the U.S. government provide financial reparations to descendants of enslaved people?",
        "Should descendants of people enslaved in the U.S. receive financial reparations from the federal government?",
        "Should federal funds be used for reparations payments to descendants of enslaved Americans?",
      ],
      [
        "Religious exemptions",
        "Should businesses receive religious exemptions from laws requiring service to same-sex weddings?",
        "Should a business’s religious beliefs exempt it from requirements to serve same-sex weddings?",
        "Should laws on serving same-sex weddings allow exemptions for businesses on religious grounds?",
      ],
      [
        "Nonbinary documents",
        "Should government identity documents offer a nonbinary gender marker?",
        "Should a nonbinary option be available for gender on government-issued ID?",
        "Should people be able to select a nonbinary gender designation on official identity documents?",
      ],
      [
        "Public religious displays",
        "Should government buildings display the Ten Commandments?",
        "Should the Ten Commandments be displayed in government buildings?",
        "Is displaying the Ten Commandments in public government buildings appropriate?",
      ],
      [
        "Abortion authority",
        "Who should primarily determine abortion policy in the United States?",
        "Where should the main authority over U.S. abortion policy rest?",
        "Who should have primary control of abortion policy in the U.S.?",
        [
          "Federal lawmakers",
          "State lawmakers",
          "Patients and their clinicians",
          "Courts applying constitutional rights",
        ],
      ],
      [
        "Sex and gender in records",
        "What should government demographic records primarily record?",
        "Which information should official demographic records prioritize?",
        "What should be the main sex or gender field in government demographic data?",
        [
          "Sex recorded at birth",
          "Current gender identity",
          "Both as separate fields",
          "Neither unless specifically needed",
        ],
      ],
    ],
  ],
  [
    "Money & work",
    [
      [
        "Universal tariffs",
        "Should the United States impose a tariff on nearly all imported goods?",
        "Should almost every imported product face a U.S. tariff?",
        "Should the U.S. apply tariffs broadly across nearly all imports?",
      ],
      [
        "Billionaire wealth tax",
        "Should billionaires pay an annual tax on their net wealth?",
        "Should an annual net-wealth tax apply to billionaires?",
        "Should the net worth of billionaires be subject to a yearly tax?",
      ],
      [
        "Minimum wage",
        "Should the federal minimum wage rise automatically with inflation?",
        "Should inflation automatically increase the federal minimum wage?",
        "Should the U.S. index its federal minimum wage to inflation?",
      ],
      [
        "Four-day week",
        "Should a four-day workweek with no loss of pay become the standard?",
        "Should the standard workweek be four days while pay stays the same?",
        "Should workers normally work four days a week without a pay reduction?",
      ],
      [
        "Union organizing",
        "Should employers be prohibited from holding mandatory meetings against unionization?",
        "Should compulsory employer meetings opposing unions be banned?",
        "Should employers be barred from requiring workers to attend anti-union meetings?",
      ],
      [
        "Universal basic income",
        "Should the government pay every adult an unconditional basic income?",
        "Should every adult receive a regular government income with no conditions?",
        "Should an unconditional basic income be provided to all adults by the government?",
      ],
      [
        "Student debt cancellation",
        "Should the government cancel a substantial share of federal student loan debt?",
        "Should a large portion of federal student debt be forgiven by the government?",
        "Should the federal government write off a substantial amount of student loan debt?",
      ],
      [
        "Gig worker status",
        "Should ride-hailing drivers be classified as employees?",
        "Should people driving for ride-hailing platforms have employee status?",
        "Should ride-hailing companies treat their drivers as employees?",
      ],
      [
        "Paying for public services",
        "Which source should bear the largest share of additional taxes for expanded public services?",
        "Where should most new tax revenue for broader public services come from?",
        "What should provide the biggest portion of extra taxes used to expand public services?",
        [
          "High personal incomes",
          "Corporate profits",
          "Consumption taxes",
          "Property and wealth",
        ],
      ],
      [
        "Trade policy",
        "What should be the main priority of U.S. trade policy?",
        "Which goal should U.S. trade policy put first?",
        "What objective should guide American trade policy above the others?",
        [
          "Lower consumer prices",
          "Domestic manufacturing jobs",
          "National security",
          "Labor and environmental standards",
        ],
      ],
    ],
  ],
  [
    "Housing & cities",
    [
      [
        "More homes near transit",
        "Should cities allow apartment buildings near transit in areas zoned for single-family homes?",
        "Should single-family zoning near transit be changed to permit apartments?",
        "Should apartment construction be allowed in single-family neighborhoods close to transit?",
      ],
      [
        "Rent control",
        "Should cities limit annual rent increases on existing tenancies?",
        "Should annual rent rises for existing tenants be capped by cities?",
        "Should city governments cap how much an existing tenant’s rent can increase each year?",
      ],
      [
        "Congestion pricing",
        "Should drivers pay a fee to enter the busiest parts of a city?",
        "Should cities charge motorists for entering their most congested areas?",
        "Should access by car to the busiest urban areas carry a fee?",
      ],
      [
        "Public camping",
        "Should cities prohibit sleeping in public spaces when no shelter bed is available?",
        "Should sleeping outdoors in public be banned even when shelters have no available beds?",
        "Should a city ban public sleeping if the person has no available shelter placement?",
      ],
      [
        "Corporate home ownership",
        "Should large institutional investors be barred from buying single-family homes?",
        "Should large investment institutions be prohibited from purchasing single-family houses?",
        "Should purchases of single-family homes by large institutional investors be banned?",
      ],
      [
        "Free public transit",
        "Should public transit be free at the point of use?",
        "Should people be able to ride public transit without paying a fare?",
        "Should public transportation systems eliminate passenger fares?",
      ],
      [
        "Short-term rentals",
        "Should cities limit the number of homes used as short-term vacation rentals?",
        "Should cities cap how many residential homes become short-term holiday rentals?",
        "Should there be a city-imposed limit on homes offered as short-term vacation accommodation?",
      ],
      [
        "Office conversions",
        "Should public money subsidize converting empty offices into housing?",
        "Should the government subsidize the conversion of vacant offices to homes?",
        "Should converting unused office space into homes receive public financial support?",
      ],
      [
        "Housing affordability",
        "Which policy should a high-cost city prioritize to make housing more affordable?",
        "What should an expensive city do first to improve housing affordability?",
        "Which measure should take priority in addressing high urban housing costs?",
        [
          "Allow more homebuilding",
          "Expand public housing",
          "Cap rents",
          "Subsidize tenants",
        ],
      ],
      [
        "Homelessness response",
        "What should be a city’s first priority in responding to unsheltered homelessness?",
        "Which response to people living without shelter should a city prioritize?",
        "What should cities focus on first when addressing street homelessness?",
        [
          "Permanent housing",
          "Emergency shelter",
          "Treatment services",
          "Public-space enforcement",
        ],
      ],
    ],
  ],
  [
    "Climate & energy",
    [
      [
        "Carbon tax",
        "Should governments tax carbon emissions?",
        "Should emitting carbon carry a government-imposed tax?",
        "Should a tax be levied on carbon emissions?",
      ],
      [
        "New nuclear power",
        "Should governments fund the construction of new nuclear power plants?",
        "Should building new nuclear power stations receive government funding?",
        "Should public funds support new nuclear power construction?",
      ],
      [
        "New fossil fuel projects",
        "Should governments stop approving new oil and gas extraction projects?",
        "Should approvals for new oil and gas extraction projects come to an end?",
        "Should new oil and gas extraction projects no longer receive government approval?",
      ],
      [
        "Gas car phaseout",
        "Should the sale of new gasoline-only cars be phased out?",
        "Should sales of new cars powered only by gasoline be gradually ended?",
        "Should governments set a phaseout for new gasoline-only car sales?",
      ],
      [
        "Climate adaptation funding",
        "Should wealthy countries help pay for climate adaptation in poorer countries?",
        "Should richer nations contribute to the cost of climate adaptation in poorer nations?",
        "Should low-income countries receive climate adaptation funding from wealthy countries?",
      ],
      [
        "Meat emissions",
        "Should foods with high greenhouse gas emissions face an additional tax?",
        "Should an extra tax apply to food that causes high greenhouse gas emissions?",
        "Should governments tax high-emission foods at a higher rate?",
      ],
      [
        "Geoengineering research",
        "Should governments fund research into solar geoengineering?",
        "Should research on solar geoengineering receive public funding?",
        "Should public money be spent studying solar geoengineering?",
      ],
      [
        "Data center energy costs",
        "Should data centers pay the full cost of the grid upgrades they require?",
        "Should the entire cost of grid upgrades needed by data centers be charged to them?",
        "Should data center operators cover all grid-upgrade costs caused by their facilities?",
      ],
      [
        "Energy tradeoffs",
        "What should be the top priority when expanding electricity supply?",
        "Which consideration should come first in adding electricity capacity?",
        "What goal should take precedence in electricity expansion?",
        [
          "Low consumer prices",
          "Low carbon emissions",
          "Reliable supply",
          "Energy independence",
        ],
      ],
      [
        "Climate policy tools",
        "Which policy should lead a country’s effort to reduce emissions?",
        "What should be the primary policy instrument for cutting national emissions?",
        "Which approach should a country prioritize in its emissions-reduction strategy?",
        [
          "Carbon pricing",
          "Clean-energy subsidies",
          "Direct emissions limits",
          "Public clean-energy investment",
        ],
      ],
    ],
  ],
  [
    "Health & bioethics",
    [
      [
        "Universal coverage",
        "Should every U.S. resident be guaranteed health coverage?",
        "Should health coverage be guaranteed to everyone living in the United States?",
        "Should the U.S. ensure that all residents have healthcare coverage?",
      ],
      [
        "Vaccine requirements",
        "Should routine childhood vaccinations be required for school attendance, with medical exemptions?",
        "Should attending school require routine childhood vaccines unless a medical exemption applies?",
        "Should schools require standard childhood immunizations while allowing medical exemptions?",
      ],
      [
        "Assisted dying",
        "Should mentally competent adults with terminal illnesses have access to medical assistance in dying?",
        "Should terminally ill adults with decision-making capacity be allowed medical assistance to end their lives?",
        "Should medical aid in dying be legally available to terminally ill adults who can make informed decisions?",
      ],
      [
        "Organ compensation",
        "Should living kidney donors be allowed to receive financial compensation?",
        "Should people who donate a kidney while alive be permitted payment?",
        "Should financial payment to living kidney donors be legal?",
      ],
      [
        "Drug price negotiation",
        "Should the U.S. government negotiate prices for prescription drugs it pays for?",
        "Should prescription medicines funded by the U.S. government have negotiated prices?",
        "Should federal purchasers negotiate the price of the prescription drugs they cover?",
      ],
      [
        "Public health mandates",
        "Should governments be able to require masks during severe respiratory disease outbreaks?",
        "Should severe respiratory outbreaks allow governments to mandate face masks?",
        "Should the government have authority to impose mask requirements in a serious respiratory outbreak?",
      ],
      [
        "Embryo gene editing",
        "Should editing human embryos to prevent serious inherited diseases be permitted?",
        "Should gene editing of human embryos be allowed to prevent severe hereditary illness?",
        "Should it be legal to alter embryo genes to avoid serious inherited disease?",
      ],
      [
        "Weight-loss drugs",
        "Should public health insurance cover weight-loss medication for people with obesity?",
        "Should people with obesity receive coverage for weight-loss drugs through public insurance?",
        "Should government health insurance pay for obesity medications used for weight loss?",
      ],
      [
        "Healthcare system",
        "Which health insurance system should the United States pursue?",
        "What model of health insurance should the U.S. adopt?",
        "Which approach to organizing U.S. health insurance is preferable?",
        [
          "Single public insurer",
          "Public option alongside private insurance",
          "Regulated private insurers",
          "Mostly unregulated private insurance",
        ],
      ],
      [
        "Drug policy",
        "How should possession of small quantities of illegal drugs for personal use be handled?",
        "What should the legal response be to possessing a small amount of an illegal drug for one’s own use?",
        "Which approach should apply to small-scale possession of illegal drugs for personal consumption?",
        [
          "Criminal penalties",
          "Civil fines",
          "Treatment referral without criminal penalties",
          "No penalty",
        ],
      ],
    ],
  ],
  [
    "Schools & knowledge",
    [
      [
        "Phones in schools",
        "Should students be prohibited from using smartphones during the school day?",
        "Should smartphone use by students be banned throughout the school day?",
        "Should schools disallow students’ smartphone use for the duration of the school day?",
      ],
      [
        "Private school vouchers",
        "Should public funds help families pay for private school tuition?",
        "Should families receive government support for private school fees?",
        "Should taxpayer funding subsidize tuition at private schools?",
      ],
      [
        "Legacy admissions",
        "Should colleges give admissions preferences to children of alumni?",
        "Should being the child of an alumnus improve an applicant’s chances of college admission?",
        "Should universities favor applicants whose parents attended the institution?",
      ],
      [
        "Standardized testing",
        "Should universities require standardized test scores for undergraduate admissions?",
        "Should standardized tests be a compulsory part of college applications?",
        "Should submitting standardized test results be required to apply for undergraduate study?",
      ],
      [
        "AI homework",
        "Should students be allowed to use generative AI for homework if they disclose it?",
        "Should disclosed use of generative AI be permitted on homework assignments?",
        "Should schools allow AI-assisted homework when students acknowledge using it?",
      ],
      [
        "Library book removals",
        "Should parents be able to require a public school library to remove a book for all students?",
        "Should a parent’s request be sufficient to remove a book from a public school library for everyone?",
        "Should parents have the power to make a school library withdraw a title from access by all students?",
      ],
      [
        "Free public college",
        "Should tuition at public colleges be free for all domestic students?",
        "Should all domestic students attend public colleges without paying tuition?",
        "Should public universities waive tuition for every domestic student?",
      ],
      [
        "Institutional neutrality",
        "Should universities avoid taking official positions on disputed political issues?",
        "Should universities remain officially neutral on contested political questions?",
        "Should a university refrain from institutional statements supporting one side of a political dispute?",
      ],
      [
        "School funding",
        "What should be the primary basis for allocating public school funding?",
        "Which principle should chiefly determine how public school money is distributed?",
        "What should drive the allocation of public education funding?",
        [
          "Equal funding per student",
          "Greater funding for higher student needs",
          "Local property-tax revenue",
          "School performance",
        ],
      ],
      [
        "Campus protests",
        "How should universities respond to peaceful protest encampments that violate campus rules?",
        "What should universities do about nonviolent protest camps that break campus regulations?",
        "Which response fits a peaceful campus encampment that is against university rules?",
        [
          "Allow them to continue",
          "Negotiate a time limit",
          "Remove them using campus staff",
          "Request police removal",
        ],
      ],
    ],
  ],
  [
    "Justice & security",
    [
      [
        "Death penalty",
        "Should the death penalty be abolished?",
        "Should capital punishment be ended?",
        "Should governments stop using the death penalty?",
      ],
      [
        "Cash bail",
        "Should cash bail be eliminated for people accused of nonviolent offenses?",
        "Should people charged with nonviolent crimes no longer have to pay cash bail?",
        "Should the use of money bail end for nonviolent criminal charges?",
      ],
      [
        "Police immunity",
        "Should police officers lose qualified immunity in civil rights lawsuits?",
        "Should qualified immunity no longer protect police in civil rights cases?",
        "Should police be unable to invoke qualified immunity against civil rights claims?",
      ],
      [
        "Facial recognition",
        "Should police be allowed to use facial recognition in public spaces?",
        "Should law enforcement have permission to deploy facial recognition in public places?",
        "Should the use of facial recognition by police in public areas be permitted?",
      ],
      [
        "Gun purchase checks",
        "Should every firearm purchase require a background check?",
        "Should background checks be mandatory for all gun purchases?",
        "Should buying any firearm be conditional on a background check?",
      ],
      [
        "Assault-style rifles",
        "Should civilian sales of semiautomatic rifles with military-style features be banned?",
        "Should semiautomatic rifles with military-style features be prohibited from sale to civilians?",
        "Should civilians be barred from buying military-style semiautomatic rifles?",
      ],
      [
        "Private prisons",
        "Should governments be prohibited from using privately operated prisons?",
        "Should private prison contracts be banned for governments?",
        "Should governments stop placing prisoners in facilities run by private companies?",
      ],
      [
        "Voting after conviction",
        "Should people regain the right to vote after completing a prison sentence?",
        "Should finishing a prison sentence restore a person’s voting rights?",
        "Should the right to vote return when someone completes their term in prison?",
      ],
      [
        "Public safety budgets",
        "Where should additional city public-safety funding primarily go?",
        "What should receive the largest share of a city’s new public-safety spending?",
        "Which use should take priority for extra municipal public-safety funds?",
        [
          "Police staffing",
          "Mental health crisis response",
          "Youth and violence prevention",
          "Housing and social services",
        ],
      ],
      [
        "Sentencing priorities",
        "What should be the main goal of criminal sentencing?",
        "Which objective should criminal sentences prioritize?",
        "What purpose should take precedence when sentencing someone for a crime?",
        ["Deterrence", "Rehabilitation", "Retribution", "Incapacitation"],
      ],
    ],
  ],
  [
    "World & conflict",
    [
      [
        "Military aid to Ukraine",
        "Should the United States continue providing military aid to Ukraine?",
        "Should U.S. military assistance to Ukraine continue?",
        "Should America keep supplying Ukraine with military aid?",
      ],
      [
        "Conditions on aid to Israel",
        "Should U.S. military aid to Israel be conditional on compliance with international humanitarian law?",
        "Should Israel’s adherence to international humanitarian law be a condition of U.S. military assistance?",
        "Should the United States tie military support for Israel to compliance with international humanitarian law?",
      ],
      [
        "Palestinian statehood",
        "Should the United States recognize a Palestinian state?",
        "Should the U.S. formally recognize Palestine as a state?",
        "Should official U.S. recognition be extended to Palestinian statehood?",
      ],
      [
        "Congress and war",
        "Should U.S. military action against Iran require prior congressional authorization except in immediate self-defense?",
        "Should Congress have to authorize attacks on Iran in advance unless the U.S. is acting in immediate self-defense?",
        "Should prior approval from Congress be required for U.S. action against Iran outside immediate self-defense?",
      ],
      [
        "Taiwan defense",
        "Should the United States commit to defending Taiwan militarily if it is invaded?",
        "Should the U.S. promise military defense of Taiwan in the event of an invasion?",
        "Should America pledge to use its military to defend Taiwan against invasion?",
      ],
      [
        "Autonomous weapons",
        "Should weapons be prohibited from selecting and attacking human targets without human approval?",
        "Should human authorization be required before a weapon selects and attacks a person?",
        "Should weapons that choose and attack people without human approval be banned?",
      ],
      [
        "International courts",
        "Should the United States accept the jurisdiction of the International Criminal Court?",
        "Should the U.S. submit to the International Criminal Court’s jurisdiction?",
        "Should America recognize the authority of the International Criminal Court over it?",
      ],
      [
        "Nuclear deterrence",
        "Should countries that possess nuclear weapons work toward eliminating them?",
        "Should nuclear-armed states pursue the elimination of their nuclear arsenals?",
        "Should states with nuclear weapons seek to get rid of those weapons?",
      ],
      [
        "Security strategy",
        "What should be the main focus of U.S. foreign policy?",
        "Which objective should lead American foreign policy?",
        "What should be the top priority of the United States in international affairs?",
        [
          "Protecting national interests",
          "Defending democratic allies",
          "Promoting human rights",
          "Avoiding military involvement",
        ],
      ],
      [
        "Responding to aggression",
        "Which tool should be used first in response to a state invading another country?",
        "What should the first international response to a cross-border invasion be?",
        "Which measure should take initial priority when one country invades another?",
        [
          "Diplomatic negotiations",
          "Economic sanctions",
          "Military aid to the invaded country",
          "Direct military intervention",
        ],
      ],
    ],
  ],
];

export const seeds: Seed[] = groups.flatMap(([category, rows], gi) =>
  rows.map(([title, question, first, second, options], i) => ({
    id: `seed-${gi + 1}-${i + 1}`,
    title,
    category,
    question,
    variants: [first, second],
    options,
  })),
);
export const categories = groups.map(([category]) => category);
export const curatedDate = "September 19, 2026";
export const sources = [
  {
    title: "The issues shaping the 2026 U.S. midterms",
    publisher: "The Week · September 2, 2026",
    url: "https://theweek.com/politics/issues-that-will-determine-2026-midterms-israel-immigration-gas-trump-iran",
    note: "Context for the library’s focus on affordability, immigration, data centers, gender policy, and foreign affairs.",
  },
  {
    title: "Europe’s debates on technology, security, and energy",
    publisher: "Le Monde · September 16, 2026",
    url: "https://www.lemonde.fr/en/international/article/2026/09/16/as-far-right-gains-ground-eu-commission-president-pledges-a-europe-that-protects_6757608_4.html",
    note: "Context for European debates on AI, social media, energy, climate, and Ukraine.",
  },
  {
    title: "Jev’s documented limitations",
    publisher: "TypeSafe · reviewed September 17, 2026",
    url: "https://docs.typesafe.ai/model-jaggedness/jev-1.13",
    note: "Framing sensitivity, literal interpretation, and inconsistencies between related questions.",
  },
  {
    title: "How Choice probabilities work",
    publisher: "TypeSafe documentation",
    url: "https://docs.typesafe.ai/primitives/choice",
    note: "A distribution over the answer options provided, with confidence derived from that distribution.",
  },
  {
    title: "OpenRouter Decisions API specification",
    publisher: "OpenRouter",
    url: "https://openrouter.ai/openapi.json",
    note: "The request and response contract used by this app: POST /api/alpha/decisions.",
  },
];
